In [21]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv("../data/raw/fut_prices_raw.csv")

In [23]:
#amount of data with a price of 0
df[df["price"] == 0]

      player_id        player_name        date  price
300          39       lionel-messi  2024-07-18      0
301          39       lionel-messi  2024-07-19      0
310          39       lionel-messi  2024-07-28      0
314          39       lionel-messi  2024-08-01      0
324          39       lionel-messi  2024-08-11      0
...         ...                ...         ...    ...
3619        227  federico-valverde  2024-09-17      0
3978         52         ter-stegen  2024-09-14      0
3979         52         ter-stegen  2024-09-15      0
3980         52         ter-stegen  2024-09-16      0
3981         52         ter-stegen  2024-09-17      0

[89 rows x 4 columns]

In [24]:
#replacing prices with values of zero with NaN as they are missing data
df["price"] = df["price"].replace(0, np.nan)
#quick check
df[df["price"] == 0]

Empty DataFrame
Columns: [player_id, player_name, date, price]
Index: []

In [25]:
#As we are dealing with time series data, we need to make sure it is sorted properly
df = df.sort_values(["player_id", "date"])
df.head()

   player_id   player_name        date     price
0         39  lionel-messi  2023-09-21  661957.0
1         39  lionel-messi  2023-09-22  159944.0
2         39  lionel-messi  2023-09-23  172778.0
3         39  lionel-messi  2023-09-24  215429.0
4         39  lionel-messi  2023-09-25  262156.0

In [26]:
#this will fill the missing values with the data of the previous time
df["price"] = df.groupby("player_id")["price"].ffill()

In [27]:
#this will fill the missing values with the data of the future time (used when there are days missing at the beginning)
df["price"] = df.groupby("player_id")["price"].bfill()

In [28]:
df["pct_change"] = df.groupby("player_id")["price"].pct_change()
df["pct_change"] = df["pct_change"].clip(-1, 1)

In [29]:
df.head()

   player_id   player_name        date     price  pct_change
0         39  lionel-messi  2023-09-21  661957.0         NaN
1         39  lionel-messi  2023-09-22  159944.0   -0.758377
2         39  lionel-messi  2023-09-23  172778.0    0.080241
3         39  lionel-messi  2023-09-24  215429.0    0.246854
4         39  lionel-messi  2023-09-25  262156.0    0.216902

In [30]:
df.isna().sum()

player_id       0
player_name     0
date            0
price           0
pct_change     11
dtype: int64

In [31]:
df.describe()

         player_id         price   pct_change
count  3982.000000  3.982000e+03  3971.000000
mean    156.454545  4.974945e+04     0.003133
std     105.127307  1.190816e+05     0.141294
min      39.000000  9.300000e+02    -0.815000
25%      50.000000  8.330750e+03    -0.050816
50%     150.000000  1.875750e+04     0.000000
75%     243.000000  3.374750e+04     0.046462
max     320.000000  1.705882e+06     1.000000

In [32]:
#Save the cleaned dataset
df.to_csv("../data/processed/fut_prices_clean.csv", index= False)